FROM python:3.14-slim
WORKDIR /app
COPY pyproject.toml README.md ./
COPY src/ ./src/
RUN pip install --no-cache-dir .
COPY models/ /app/models/
EXPOSE 8000
CMD ["uvicorn","prodml.api.main:app","--host","0.0.0.0","--port","8000"]
